version: "3.7"

services: 
    backend:
      image: flask-backend
      build: ./backend
      depends_on:
        - frontend
      networks:
        - app_network
      ports:
        - '8888:8888'
    frontend:
      image: react-frontend
      build: ./frontend
      depends_on:
        - backend
networks:
  app_network:
    driver: bridge